---
title: "Product Backlog"

---

### Backlog de Funcionalidades

Pendiente: Implementar tras hacer el mockup

[Kanban](https://github.com/users/daviddevops96/#projects/1)

# Nombre del proyecto: SummonerMatch

**Descripción**: Una plataforma que permite a los jugadores crear o unirse a partidas del LoL (League Of Legends).

**Propósito**: Que cualquier jugador pueda jugar con otras personas con el fin de mejorar su experiencia de juego y trabajo en equipo.

**User Stories**
Descripciones breves de las funcionalidades desde la perspectiva del usuario. Siguen el formato:

- "Como [usuario], quiero [poder registrarme de manera sencilla y personalizada] para [poder usar de manera inmediata la web]"
        
- "Como [usuario], quiero [iniciar sesion rapidamente] para [unirme a las partidas en las que quiero participar]"
        
- "Como [usuario], quiero [poder consultar mis partidas en mi perfil] para [tener en cuenta a que partidas estoy apuntado]"
    
**Tareas**
    - Desglose detallado de las acciones necesarias para completar las User Stories

## Ingreso y Registro:

En el menu del header un boton para registrarme o iniciar sesión  para poder crear partidas para que otras personas se unan o buscar partidas a las que unirme. Esto abrirá un modal de registro.
Como usuario, quiero registrarme con la siguiente información: userName, Pass, email, nickName, posicion(opcional), rango(opcional), regionServidor  Imagen (opcional).
Como usuario registrado, deseo poder modificar mis detalles, incluyendo userName, Pass, email, nickName, posicion, rango, y regionServidor.
Como usuario registrado, quiero tener la opción de darme de baja de la plataforma mediante un botón(igual que GitHub).
En caso de olvidar la contraseña, recuperar cuenta
Quiero poder desconectarme (boton cerrar sesion) de mi cuenta de usuario.


## Interfaz Principal:

El menú principal estará inicialmente formado por (X) Cardview Recientes, que desaparecerán a medida que se llenen. Esta personalización se mantendrá a nivel de usuario.

En caso de tener la sesión iniciada:
Como usuario, quiero que cada tarjeta (CARD) sea seleccionable, llevándome a una página con detalles adicionales y la opción de unirme.
Tener acceso al perfil de usuario  al hacer clic en mi foto de perfil
Crear una partida (Tiempo límite desde creación 20mins)
En caso de no haber iniciado sesión:
Poder acceder a las partidas (CARD) pero no poder unirte a ellas
En vez de qué aparezca la opción del acceso al usuario, 2 botones (iniciar sesión, registrarse)
Bloque qué muestre una breve explicación de la plataforma.
Filtrar estas partidas (Cantidad jugadores [mayor, menor], rango, región).

Y en la parte superior tener un botón para redireccionar a la búsqueda de usuarios.

## CARD PARTIDA e Interacción:

Vida de 20 minutos
En la página de partidas (CARDS) a los que estoy inscrito, quiero tener la opción de abandonar un grupo a través de un botón específico.
También, deseo contar con un chat para interactuar con los miembros del grupo.
Una partida (CARD) (Fuera) contiene información como posiciones, rango de la partida, tipo de partida.
Una partida (Dentro) contiene información como posiciones, rango de la partida, tipo de partida (por ejemplo, partidas de LoL), usuarios, botón chat, botón Abandonar Partida si soy miembro, si soy OWNER botón disolver partida.
Consultas a la API de LoL para hacer la validación del ganador

## CARD TORNEO e Interacción:(mismas especificaciones de Partida)

Los torneos los crea el administrador manualmente (Hora y Dia)
Mínimo 4 equipos por torneo
Tiempo de inscripción de 3h
Los cierra el administrador

## ODS

### ODS 3: Salud y Bienestar:

Fomentar la colaboración y el trabajo en equipo en actividades físicas y deportivas puede contribuir al bienestar general y a una vida saludable.

### ODS 5: Igualdad de Género:

Promover la igualdad de género en la formación y participación de equipos puede ser un aspecto relevante, fomentando la inclusión de todos los géneros.

### ODS 10: Reducción de las Desigualdades:

Si tu proyecto busca reducir las brechas y promover la igualdad de oportunidades en la formación de equipos, podría alinearse con este objetivo.

### ODS 17: Alianzas para lograr los Objetivos:

Fomentar la cooperación y las alianzas entre jugadores y equipos puede contribuir a la creación de alianzas para lograr los objetivos, promoviendo la colaboración global.
